//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabiane_Sistema_CaixaDiario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competencia()
        {
            this.MovimentacaosComp = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CompNome { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public string Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> MovimentacaosComp { get; set; }
    }
}
