//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabiane_Sistema_CaixaDiario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> TipoMovimentacao_fk { get; set; }
        public Nullable<int> ParteEnvolvida_fk { get; set; }
        public Nullable<int> Competencia_fk { get; set; }
        public Nullable<int> Empresa_fk { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public string Usuario { get; set; }
    
        public virtual Competencia Competencia { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ParteEnvolvida ParteEnvolvida { get; set; }
        public virtual TipoMovimentacao TipoMovimentacao { get; set; }
    }
}
