//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabiane_Sistema_CaixaDiario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteEnvolvida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParteEnvolvida()
        {
            this.MovimentacaosPEnv = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<int> TipoParteEnvolvida_fk { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public Nullable<decimal> Fone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public string Usuario { get; set; }
    
        public virtual TipoParteEnvolvida TipoParteEnvolvida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> MovimentacaosPEnv { get; set; }
    }
}
