//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabiane_Sistema_CaixaDiario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMovimentacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoMovimentacao()
        {
            this.MovimentacaosTpMov = new HashSet<Movimentacao>();
        }
    
        public int Id { get; set; }
        public string TipoMovimentacao1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimentacao> MovimentacaosTpMov { get; set; }
    }
}
